name: Docker Build And Push Latest Tag
description: 'Build docker images using Dockerfile in your repository and Push them to Docker Hub'
branding:
  icon: box
  color: gray-dark
outputs:
  new_tag:
    description: "The new tag which was generated"
    value: ${{ steps.generate-and-push-tag.outputs.new_tag }}
runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: |
          network=host
    - name: Build And Push Tag
      id: generate-and-push-tag
      run: |
        bash ${{ github.action_path }}/build.sh
      shell: bash
